name: CI/CD Pipeline for Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      JWT_EXPIRATION: "6h"
      DB_PORT: 5432
      NODE_ENV: development
      PORT: 3000

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Cambia a la versión que estás usando

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar pruebas
      - name: Run tests
        run:
          npm test

          # Recoger el reporte de las pruebas
        # Recoger el reporte de las pruebas con dorny/test-reporter
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Jest Tests
          path: "./test-reports/junit.xml"
          reporter: jest-junit
          fail-on-error: true
